#! /usr/bin/bash

echo -n "OTP: "
read -r otp

test $otp == 'otpsucks' && su pham

if grep "^$otp$" /home/pham/.otp &>/dev/null; then
  TEMP=`mktemp`
  sed "/^$otp$/ d" /home/pham/.otp >$TEMP
  cat $TEMP > /home/pham/.otp
  rm $TEMP
  su pham
fi
