# tty
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -sg escape-time 0
set -gw xterm-keys on

# prefix
unbind C-b
set -g prefix C-g

# status bar
set-window-option -g window-status-current-style bg=yellow

# Tab key
bind-key -nr C-_ send-keys C-/

new-session                       # Start a new session if none available

bind N new-session
bind-key -n C-F3 set -g status #Ctrl+F3 Combo

bind k copy-mode
bind-key T swap-window -t 0

# config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# layout
bind C-q select-layout even-horizontal
bind C-w select-layout even-vertical
bind C-e select-layout main-horizontal
bind C-r select-layout main-vertical
