-- we can read Lua syntax here!
return {
    ["BookShortcuts_directory_action"] = "FM",
    ["SSH_allow_no_password"] = true,
    ["activate_menu"] = "swipe",
    ["auto_disable_wifi"] = true,
    ["auto_save_settings_interval_minutes"] = 15,
    ["auto_standby_timeout_seconds"] = -1,
    ["auto_suspend_timeout_seconds"] = 900,
    ["autodim_duration_seconds"] = 5,
    ["autodim_fraction"] = 20,
    ["autodim_starttime_minutes"] = -1,
    ["autoshutdown_timeout_seconds"] = -1,
    ["autoturn_distance"] = 1,
    ["autoturn_enabled"] = false,
    ["autoturn_timeout_seconds"] = 5,
    ["autowarmth_fl_off_during_day_offset_s"] = 0,
    ["avoid_flashing_ui"] = true,
    ["back_in_filemanager"] = "parent_folder",
    ["back_in_reader"] = "default",
    ["back_to_exit"] = "disable",
    ["bookmarks_items_font_size"] = 19,
    ["bookmarks_items_per_page"] = 14,
    ["calibre_opds"] = {},
    ["closed_rotation_mode"] = 0,
    ["copt_font_gamma"] = 43,
    ["copt_h_page_margins"] = {
        [1] = 20,
        [2] = 20,
    },
    ["copt_line_spacing"] = 115,
    ["copt_status_line"] = 1,
    ["coverbrowser_initial_default_setup_done"] = true,
    ["cre_font_family_fonts"] = {},
    ["cre_header_auto_refresh"] = 1,
    ["cre_header_battery"] = 1,
    ["cre_header_battery_percent"] = 0,
    ["cre_header_chapter_marks"] = 1,
    ["cre_header_clock"] = 1,
    ["cre_header_page_count"] = 1,
    ["cre_header_page_number"] = 1,
    ["cre_header_reading_percent"] = 0,
    ["cre_header_title"] = 1,
    ["default_highlight_action"] = "dictionary",
    ["dev_no_c_blitter"] = false,
    ["device_id"] = "2F1B2BBA7854401D999E14DD76377039",
    ["device_status_battery_alarm"] = true,
    ["device_status_battery_interval_minutes"] = 15,
    ["device_status_battery_threshold"] = 10,
    ["device_status_battery_threshold_high"] = 100,
    ["device_status_memory_interval_minutes"] = 5,
    ["device_status_memory_threshold"] = 100,
    ["dicts_disabled"] = {},
    ["dicts_order"] = {},
    ["duration_format"] = "classic",
    ["end_document_action"] = "mark_read",
    ["exporter"] = {
        ["html"] = {
            ["enabled"] = false,
        },
        ["joplin"] = {
            ["enabled"] = false,
        },
        ["json"] = {
            ["enabled"] = false,
        },
        ["markdown"] = {
            ["formatting_options"] = {
                ["invert"] = "bold",
                ["lighten"] = "italic",
                ["strikeout"] = "strikethrough",
                ["underscore"] = "underline_markdownit",
            },
            ["highlight_formatting"] = true,
        },
        ["readwise"] = {
            ["enabled"] = false,
        },
        ["text"] = {
            ["enabled"] = false,
        },
    },
    ["filemanagermenu_tab_index"] = 3,
    ["flash_keyboard"] = false,
    ["folder_shortcuts"] = {},
    ["footer"] = {
        ["align"] = "center",
        ["all_at_once"] = false,
        ["auto_refresh_time"] = false,
        ["battery"] = false,
        ["battery_hide_threshold"] = 100,
        ["book_chapter"] = false,
        ["book_chapter_max_width_pct"] = 30,
        ["book_time_to_read"] = false,
        ["book_title"] = false,
        ["book_title_max_width_pct"] = 30,
        ["bookmark_count"] = false,
        ["bottom_horizontal_separator"] = false,
        ["chapter_progress"] = false,
        ["chapter_time_to_read"] = false,
        ["container_bottom_padding"] = 1,
        ["container_height"] = 14,
        ["disable_progress_bar"] = false,
        ["disabled"] = false,
        ["frontlight"] = false,
        ["hide_empty_generators"] = false,
        ["item_prefix"] = "icons",
        ["items_separator"] = "bar",
        ["lock_tap"] = false,
        ["mem_usage"] = false,
        ["page_progress"] = true,
        ["pages_left"] = false,
        ["pages_left_book"] = false,
        ["pages_left_includes_current_page"] = false,
        ["percentage"] = false,
        ["progress_bar_min_width_pct"] = 20,
        ["progress_bar_position"] = "alongside",
        ["progress_margin"] = false,
        ["progress_margin_width"] = 24,
        ["progress_pct_format"] = "0",
        ["progress_style_thick_height"] = 7,
        ["progress_style_thin"] = false,
        ["progress_style_thin_height"] = 3,
        ["reclaim_height"] = false,
        ["skim_widget_on_hold"] = false,
        ["text_font_bold"] = false,
        ["text_font_size"] = 14,
        ["time"] = true,
        ["toc_markers"] = true,
        ["toc_markers_width"] = 2,
        ["wifi_status"] = false,
    },
    ["frontlight_intensity"] = 15,
    ["frontlight_warmth"] = 0,
    ["ges_tap_interval_on_keyboard_ms"] = 0,
    ["highlight_lighten_factor"] = 0.2,
    ["highlight_long_hold_threshold_s"] = 3,
    ["history_filter"] = "all",
    ["hold_pan_rate"] = 5,
    ["home_dir"] = "/mnt/onboard/books",
    ["inertial_scroll"] = false,
    ["input_ignore_gsensor"] = true,
    ["is_frontlight_on"] = false,
    ["keyboard_key_font_size"] = 22,
    ["keyboard_layout"] = "en",
    ["keyboard_layouts"] = {},
    ["language"] = "C",
    ["last_migration_date"] = 20221027,
    ["lastdir"] = "/mnt/onboard/books",
    ["lastfile"] = "/mnt/onboard/books/unix/ascii.txt",
    ["low_pan_rate"] = false,
    ["menu_search_string"] = "幫助",
    ["metric_length"] = true,
    ["multiswipes_enabled"] = false,
    ["opds_servers"] = {
        [1] = {
            ["title"] = "Project Gutenberg",
            ["url"] = "https://m.gutenberg.org/ebooks.opds/?format=opds",
        },
        [2] = {
            ["title"] = "Standard Ebooks",
            ["url"] = "https://standardebooks.org/feeds/opds",
        },
        [3] = {
            ["title"] = "Feedbooks",
            ["url"] = "https://catalog.feedbooks.com/catalog/public_domain.atom",
        },
        [4] = {
            ["title"] = "ManyBooks",
            ["url"] = "http://manybooks.net/opds/index.php",
        },
        [5] = {
            ["title"] = "Internet Archive",
            ["url"] = "https://bookserver.archive.org/",
        },
        [6] = {
            ["title"] = "textos.info (Spanish)",
            ["url"] = "https://www.textos.info/catalogo.atom",
        },
        [7] = {
            ["title"] = "Gallica (French)",
            ["url"] = "https://gallica.bnf.fr/opds",
        },
    },
    ["page_turns_tap_zones"] = "default",
    ["panel_zoom_enabled"] = {
        ["cbt"] = true,
        ["cbz"] = true,
    },
    ["panel_zoom_fallback_to_text_selection"] = {
        ["pdf"] = true,
    },
    ["plugins_disabled"] = {
        ["calibre"] = true,
        ["calibrecompanion"] = true,
        ["evernote"] = true,
        ["exporter"] = true,
        ["externalkeyboard"] = true,
        ["goodreads"] = true,
        ["japanese"] = true,
        ["keepalive"] = true,
        ["kobolight"] = true,
        ["movetoarchive"] = true,
        ["opds"] = true,
        ["readtimer"] = true,
        ["send2ebook"] = true,
        ["storagestat"] = true,
        ["vocabbuilder"] = true,
        ["zsync"] = true,
    },
    ["quickstart_shown_version"] = 202301000000,
    ["reader_footer_custom_text"] = "KOReader",
    ["reader_footer_custom_text_repetitions"] = "1",
    ["reader_footer_mode"] = 0,
    ["save_document"] = "prompt",
    ["screensaver_delay"] = "disable",
    ["screensaver_hide_fallback_msg"] = false,
    ["screensaver_image"] = "/mnt/onboard/screenshots/Reader_2023-02-15_140821.png",
    ["screensaver_img_background"] = "black",
    ["screensaver_message_position"] = "bottom",
    ["screensaver_msg_background"] = "none",
    ["screensaver_show_message"] = true,
    ["screensaver_stretch_images"] = false,
    ["screensaver_type"] = "image_file",
    ["screenshot_dir"] = "/mnt/onboard/screenshots/",
    ["scroll_method"] = "classic",
    ["shorten_home_dir"] = false,
    ["show_bottom_menu"] = false,
    ["show_hidden"] = true,
    ["show_unsupported"] = true,
    ["start_with"] = "filemanager",
    ["statistics"] = {
        ["calendar_browse_future_months"] = false,
        ["calendar_nb_book_spans"] = 3,
        ["calendar_show_histogram"] = true,
        ["calendar_start_day_of_week"] = 2,
        ["convert_to_db"] = true,
        ["is_enabled"] = true,
        ["max_sec"] = 120,
        ["min_sec"] = 5,
    },
    ["style_tweaks"] = {
        ["footnote-inpage_epub_smaller"] = true,
        ["footnote-inpage_fb2"] = true,
    },
    ["style_tweaks_in_dispatcher"] = {},
    ["terminal_buffer_size"] = 16,
    ["terminal_font_size"] = 16,
    ["terminal_shell"] = "sh",
    ["text_lang_fallback"] = "en-US",
    ["toc_items_per_page"] = 14,
    ["vocabulary_builder"] = {
        ["enabled"] = true,
    },
    ["wifi_disable_action"] = "leave_on",
    ["wifi_was_on"] = false,
}
