#!/bin/bash

github_api_token=$(cat $SETTING_DIR/tokens/github)

function _update(){
    curl -s -H "Authorization: OAuth $github_api_token" https://api.github.com/users/typebrook/gists |\
    jq '.[] | "\( .html_url ) \(.files | keys | length) \( .description )"' |\
    tr -d '"' | tac | nl |\
    while read line_num link file_num description; do
        echo $line_num $link $file_num $(echo $description | cut -c -70)
    done | tee ~/.gist
}

case "$1" in
  update | u)
    _update
    ;;

  *)
    cat ~/.gist
    ;;
esac
