#! /bin/bash

OSM_USER_PASSWD=$(cat ~/git/settings/tokens/osm)

#server=https://master.apis.dev.openstreetmap.org
server=https://api.openstreetmap.org
comment="change is_in format"

for i in "$@"
do
case $i in
    -s)
    lon_col=0; lat_col=1
    shift;;

    *)
    csv=$i
    shift;;
esac
done

info="<osm>
        <changeset> 
          <tag k='comment' v='$comment'/> 
        </changeset> 
      </osm> 
     "

echo $info |\
curl -u $OSM_USER_PASSWD -i --upload-file - $server/api/0.6/changeset/create |\
tee /dev/tty |\
tail -1 |\
xsel -ib

