#! /bin/bash

echo --------------
head -1 $1 | sed 's/,/ /g'
echo --------------
echo 

read -p "Number of latitude column: " lat_col
read -p "Number of longitude column: " lon_col

sed 's/[^,]*/"\0"/g' $1 |\
sed 's/.*/[\0]/g' |\
sed '1d' |\
jq '. | {"type": "Feature",  "properties": {},  "geometry":{ "type": "Point",  "coordinates": [(.[-1] | tonumber), (.[-2] | tonumber)] } }'|\
jq -s '{"type": "FeatureCollection", "features": .}'
