[font]
size = 18

[font.bold]
family = "SauceCodePro Nerd Font Mono"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"

[font.italic]
family = "SauceCodePro Nerd Font Mono"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
