#! /bin/bash

if [[ ! $1 =~ '.md' ]]; then
  echo markdown file is not given >&2
  exit 1
fi

# Available themes:
# beige black blood league moon night serif simple sky solarized white
THEME=${THEME:-serif}

# Available highlight theme:
# a11y-dark a11y-light agate androidstudio an-old-hope
# arduino-light arta ascetic atom-one-dark atom-one-dark-reasonable
# atom-one-light base16 brown-paper brown-papersq.png codepen-embed
# color-brewer dark default devibeans docco
# far felipec foundation github github-dark github-dark-dimmed
# gml googlecode gradient-dark gradient-light grayscale hybrid
# idea intellij-light ir-black isbl-editor-dark isbl-editor-light kimbie-dark
# kimbie-light lightfair lioshi magula mono-blue monokai
# monokai-sublime night-owl nnfx-dark nnfx-light nord obsidian
# panda-syntax-dark panda-syntax-light paraiso-dark paraiso-light pojoaque
# pojoaque.jpg purebasic qtcreator-dark qtcreator-light rainbow
# routeros school-book shades-of-purple srcery stackoverflow-dark
# stackoverflow-light sunburst tokyo-night-dark tokyo-night-light tomorrow-night-blue
# tomorrow-night-bright vs2015 vs xcode xt256
HIGHLIGHT_THEME=${HIGHLIGHT_THEME:-base16/zenburn}

docker run --rm \
  -u `id -u`:`id -g` \
  -v `pwd`:/slides \
  -p 1948:1948 \
  webpronl/reveal-md:5.3.4 \
    $1 \
    --static /slides \
    #--theme ${THEME} \
    #--highlight-theme ${HIGHLIGHT_THEME} \
